// Code generated by "stringer -type Status -trimprefix Status"; DO NOT EDIT.

package kmod

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[StatusUnloaded-1]
	_ = x[StatusUnloading-2]
	_ = x[StatusLoading-3]
	_ = x[StatusLive-4]
	_ = x[StatusInUse-5]
}

const _Status_name = "UnknownUnloadedUnloadingLoadingLiveInUse"

var _Status_index = [...]uint8{0, 7, 15, 24, 31, 35, 40}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
